# bonjour.yml
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode:19"
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: docker image build --tag="${IMAGE_NAME}" ./
      
      # Ajoutez cette étape pour l'analyse Hadolint
      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: "Dockerfile" # Spécifiez le chemin vers votre Dockerfile si différent

      - run: docker container run "${IMAGE_NAME}" npm run lint
